# Render Blueprint for TimeWise HRMS Pro
# This file defines the complete infrastructure for deploying on Render

services:
  # Web Service - Next.js Application
  - type: web
    name: timewise-hrms
    env: node
    plan: free
    repo: https://github.com/ChampionKerr/timewise-hrms-pro
    branch: render-hosting
    rootDir: timewise-hrms-pro/timewise-hrms
    
    # Build Configuration with proper quoting
    buildCommand: "npm install && npm run render:build"
    startCommand: "npm run render:start"

    # Health Check
    healthCheckPath: /api/health/render

    # Environment Variables
    envVars:
      - key: NODE_ENV
        value: production

      - key: RENDER
        value: "true"

      # Database URL (automatically populated by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: timewise-postgres
          property: connectionString

      # NextAuth Configuration (user must provide)
      - key: NEXTAUTH_SECRET
        generateValue: true # Render will generate a secure random value

      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: timewise-hrms
          property: host

      # Public URL for the application
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: timewise-hrms
          property: host

      # Email Configuration (optional - user can configure)
      - key: EMAIL_FROM
        value: noreply@timewise-hrms.com

      # Optional email server configuration
      - key: EMAIL_SERVER_HOST
        # User should set this in Render dashboard

      - key: EMAIL_SERVER_PORT
        value: "587"

      - key: EMAIL_SERVER_USER
        # User should set this in Render dashboard

      - key: EMAIL_SERVER_PASSWORD
        # User should set this in Render dashboard (as secret)

    # Auto-deploy settings
    autoDeploy: true
    branch: render-hosting # Deploy from render-hosting branch

    # Resource limits (free tier)
    disk:
      name: timewise-disk
      mountPath: /opt/render/project/.next
      sizeGB: 1

    # Custom headers and configuration
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

# Database Service - PostgreSQL
databases:
  - name: timewise-postgres
    plan: free # 1GB storage, 1M rows limit
    databaseName: timewise_hrms
    user: timewise_user

    # Database configuration
    region: oregon # Choose region closest to your users
    version: "15" # PostgreSQL 15


    # Backup configuration (available on paid plans)
    # backup:
    #   schedule: "0 2 * * *"  # Daily at 2 AM
    #   retention: 7           # Keep 7 days of backups
# Optional: Redis for caching (requires paid plan)
# - type: redis
#   name: timewise-redis
#   plan: starter
#   maxmemoryPolicy: allkeys-lru
